name: Git user setup

description: Setup git user

inputs:
  user_mail:
    description: 'User email'
    required: true
  user_name:
    description: 'User name'
    required: true

runs:
  using: composite
  steps:
    - name: Set git user
      shell: bash
      run: |
        git config --local user.email "${{ inputs.user_mail }}"
        git config --local user.name "${{ inputs.user_name }}"
