# Read more on https://github.com/amannn/action-semantic-pull-request
name: 'Test Lint PR'

on:
  pull_request:
    branches: [main, master]
    types:
      - opened
      - edited
      - synchronize

jobs:
  pr-title-check-test:
    runs-on: self-hosted

    concurrency:
      group: pr-title-${{ github.head_ref }}
      cancel-in-progress: true

    steps:
      - name: Logging
        shell: bash
        run: echo "TEST"
        
      - name: semantic-pull-request
        timeout-minutes: 3
        uses: amannn/action-semantic-pull-request@v3.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
