# Read more on https://github.com/amannn/action-semantic-pull-request
name: 'Ci Playground'

on:
  issues:
    types: [opened]

jobs:
  issue_logger:
    runs-on: ubuntu-latest

    steps:
      - name: Logging
        shell: bash
        run: echo "START TEST"
        
      - name: Get issue title
        id: get_issue_title
        uses: actions/github-script@v6
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
        with:
          script: |
            const { ISSUE_TITLE } = process.env
            
            console.log(ISSUE_TITLE, '${{ github.event.issue.title }}');
            const issueTitle = {
              title: ISSUE_TITLE
            };
            
            return JSON.stringify(issueTitle);
            
      - name: Log issue title
        shell: bash
        run: echo "${{ steps.get_issue_title.outputs.result }}"
            
