# Read more on https://github.com/amannn/action-semantic-pull-request
name: 'Ci Playground'

on:
  issues:
    types: [opened]

jobs:
  issue_logger:
    runs-on: ubuntu

    steps:
      - name: Logging
        shell: bash
        run: echo "START TEST"
        
      - name: Get issue title
        id: get_issue_title
        uses: actions/github-script@v6
        with:
          script: |
            const issueTitle = {
              title: '${{ github.event.issue.title }}'
            };
            
            return JSON.stringify(issueTitle);
            
      - name: Log issue title
        shell: bash
        run: echo "${{ steps.get_issue_title.outputs.result }}"
            
