name: 'Test if std out'

on:
  workflow_dispatch:
  
jobs:
  test-if:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set variables
        id: set_var
        shell: bash
        run: |
          echo "condition1=true" >> $GITHUB_OUTPUT
          echo "condition2=false" >> $GITHUB_OUTPUT
          echo "condition3=true" >> $GITHUB_OUTPUT
      
      - name: Set data
        id: set_data
        shell: bash
        run: |
          BUILD_RESULT=success
          DEPLOY_RESULT=failure
          OVERALL_RESULT="failure"
          if [[ $BUILD_RESULT == 'success' || $BUILD_RESULT == 'skipped' && $DEPLOY_RESULT == 'success' ]]
          then
            OVERALL_RESULT="success"
          fi

          echo "status=$OVERALL_RESULT"
